import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// function RootLayout({children}) { ... } → define a component function with a prop "children"
// chilren: ... → define object type , "children" is a React.ReactNode 
// Readonly<> → wrap with Readonly , takes an object type and makes all properties read-only.

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="header">
          <a href="#">Theme</a>
          <a href="#">Docker</a>
          <a href="#">Prima</a>
          <a href="#">Test</a>
          <a href="#">About</a>
        </div>

        
        {children}

        
        <footer className="footer">
          <p>© 2025 My Website. All rights reserved.</p>
          <p>22088587</p>
          <p>Shiying Wu</p>
        </footer>
      </body>
    </html>
  );
}
